= Spring Data Demo


== Introduction
This project demonstrates the use of Spring Data to access and manipulate data in different kinds of data stores.

* Spring Data JPA for relational database
* Spring Data MongoDB for Document database
* Spring Data Neo4J for Graph database

== Models
=== User and Groups
[plantuml, data-model-user, png]
....
class UserInfo {
    <<identity>> id: Long
    dateOfBirth: Date
    emailAddress: String
    fullName: String
    <<unique>> userId: String
}
class GroupInfo {
    <<identity>> id: Long
    <<unique>> groupName: String
}

class GroupMember {
    <<identity>> id: Long
    enabled: Boolean
}

GroupInfo o-- UserInfo: groupOwner
GroupMember o-- UserInfo: member
GroupMember o-left- GroupInfo: memberOfgroup
....

=== Audit Model

[plantuml, data-model-audit, png]
....

class AuditEntry {
    <<identity>> id: String
    auditTime: Date
    auditType: String
    eventType: String
}

class AuditInfo {
    <<identity>> id: String
    name: String
    afterValue: String
    beforeValue: String
}

AuditEntry -left-* AuditInfo : auditInfo
....

=== Device Location Model
[plantuml, data-model-location, png]
....
class DeviceInfo {
    <<identity>> id: String
    <<unique>> deviceId: String
    deviceName: String
}

class LocationUpdate {
    <<identity>> id: String
    latX: double
    latY: double
    locDetail: String
    locTime: Date
}

LocationUpdate o-left- DeviceInfo: device

....